name: Bug Report
description: Report something that isn't working as expected.
title: "bug: "
labels: ["type: bug", "needs triage"]
body:
  - type: textarea
    attributes:
      label: Description
      description: What happened? Clear, concise details help us reproduce.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Given config X
        2. Run command Y
        3. See error Z
    validations:
      required: true
  - type: input
    attributes:
      label: Environment
      placeholder: "Paper 1.20.6, Kotlin 1.9.0, Adventure 4.14.0"
  - type: textarea
    attributes:
      label: Logs / Stacktrace
      render: shell
