name: Test Coverage Request
description: Request new or improved tests.
title: "test: "
labels: ["type: test", "good first issue"]
body:
  - type: textarea
    attributes:
      label: What area needs tests?
      placeholder: e.g., MiniMessage parser edge case with gradients
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why is this important?
